### PR TITLE
docs(README): moved server.connection before server.register in example

### PR DESCRIPTION
**Pull request by sebbel**

### CODE REVIEW

**Comment by gr2m** [comment]
could you please reword your commit to `docs(README): moved server.connection before server.register in example`? Sorry for the nitpicking, I can also do this for you, or help you if you don’t know how that works. The reason is that we follow [Angular’s Commit Conventions](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines)

**Comment by sebbel** [comment]
Sorry :( I was mit aware of the guidelines and will read them shortly. I have adjusted the title.

**Comment by gr2m** [comment]
no worries at all, you couldn’t have known :) it’s not about the title of the PR though, it’s about the commit message: https://github.com/hoodiehq/hoodie-server-store/commit/42f35836e328ea5e1884c35e5c6ac2f4a5cc30bc it would be great if you could reword the commit message to `docs(README): moved server.connection before server.register in example`. 

You can do that with `git commit --amend -m "docs(README): moved server.connection before server.register in example"` and then `git push --force origin master` to update your pull request

does that make sense?

**Comment by sebbel** [comment]
Oh, I edited the Readme inside github like a noob. I will redo the PR shortly and have the correct commit message

**Comment by sebbel** [comment]
Thanks for the command, I managed to rename it.

**Comment by gr2m** [comment]
Perfect, thanks! LGTM

ping @hoodiehq/maintainers for 2nd review :eyes:

**Comment by HipsterBrown** [comment]
Nice fix! LGTM :+1:

**Pull request merged**
